### ISSUE TITLE
Is it possible to segment parts of an object based on it's material? 

### ISSUE THREAD

**Issue by tgorm1965** [ZumoLabs/zpy#129]
**Is your feature request related to a problem? Please describe.**
I would like to segment a complex mesh that is made up of different components with different materials for every component. Is it possible to segment based off the material? Or do i need to separate the single mesh into multiple components?

**Comment by HugoCMU** [comment]
Segmentation is stored as a color in every vertex:

```
obj.data.sculpt_vertex_colors['category'].data[i].color = color
```
[code link](https://github.com/ZumoLabs/zpy/blob/2c9b47b2897c13c12d1d69450f42d577b0ef8f41/zpy/objects.py#L343)

You could use vertex groups [(video)](https://www.youtube.com/watch?v=OYg2fyQMtJc&ab_channel=TheCGEssentials)[(doc)](https://docs.blender.org/manual/en/latest/modeling/meshes/properties/vertex_groups/assigning_vertex_group.html) to select different parts of the object and assign it different segmentation colors.

**Comment by tgorm1965** [comment]
Het Hugo, thank you for your response. Could you give me a code example of how I'd assign the different segmentation colours to the different vertex groups in that object?

**Comment by HugoCMU** [comment]
Sure! Snippet below is how you would segment the default cube into two parts using vertex groups [(full run script here)](https://github.com/ZumoLabs/zpy/blob/main/examples/seg_vertex_group_cube/run.py).
```
    # The default cube when you open a new Blender file
    cube = bpy.data.objects['Cube']
    
    # Random boiler plate required to render out images
    zpy.material.make_aov_material_output_node(obj=cube, style='category')
    cube.data.sculpt_vertex_colors.new(name='category')

    # Make some random segmentation colors
    segmentation_color_a = zpy.color.random_color(output_style='frgba')
    segmentation_color_b = zpy.color.random_color(output_style='frgba')

    # Cubes have 8 vertices, split it into two vertex groups
    cube.vertex_groups.new(name='sideA').add([0, 1, 4, 5], weight=1.0, type='ADD')
    cube.vertex_groups.new(name='sideB').add([2, 3, 6, 7], weight=1.0, type='ADD')
    
    for vertex in cube.data.vertices:
        # Color half the cube one color
        if cube.vertex_groups['sideA'].index == vertex.groups[0].group:
            cube.data.sculpt_vertex_colors['category'].data[vertex.index].color = segmentation_color_a
        # and the other one the other color
        elif cube.vertex_groups['sideB'].index == vertex.groups[0].group:
            cube.data.sculpt_vertex_colors['category'].data[vertex.index].color = segmentation_color_b
```

Screenshot:
![image](https://user-images.githubusercontent.com/8493427/123034018-9d75c780-d39d-11eb-8064-9f15df09165b.png)

**Comment by HugoCMU** [comment]
Closing issue, but let us know if you need more guidance on this!

**Comment by tgorm1965** [comment]
Hey @HugoCMU , have you looked at the segmentation annotation for vertex group segmentation? It leaves a gap between the blended colours for me whenever I check the annotation from the coco json over the top of the rgb image. Have you figured out how to solve this?

**Comment by HugoCMU** [comment]
I found this [old reddit thread](https://www.reddit.com/r/gamedev/comments/9utkh4/getting_hard_edges_in_blender_vertex_painting_for/) which seems to be on the right trail:

> you have to select the specific faces you want to paint in edit mode, then go to vertex paint mode and enable the "face selection masking for painting option", the icon to the left of the layer buttons in the bottom bar. That way vertex painting will be constrained to the selected faces and will produce hard edges

**Comment by tgorm1965** [comment]
Hey @HugoCMU , thank you for the help! Would I have to paint the faces as well that I want manually on that paint mode?

**Comment by HugoCMU** [comment]
This seems to be the [toggle for that behavior in code](https://docs.blender.org/api/current/bpy.types.Mesh.html#bpy.types.Mesh.use_paint_mask), but I don't know if you can do it entirely in code.

**Comment by tgorm1965** [comment]
i'm happy to do it with the GUI for now. Would I just select the faces in edit mode and then go to the face paint mode and then choose the face option? Is that it? Seems like I should do something else haha

**Comment by tgorm1965** [comment]
Hey @HugoCMU, if I've manually painted the faces on my object, how would the code on the cube vertex segmentation example need to change for me to get the cseg image out?

**Comment by HugoCMU** [comment]
The [render call](https://github.com/ZumoLabs/zpy/blob/6bf7cb7db2c3e0845daf81141911db7e6a210798/examples/seg_vertex_group_cube/run.py#L42) should still output a color image and a segmentation image. If you don't see anything make sure the object has sculpt vertex colors: 
![image](https://user-images.githubusercontent.com/8493427/126019165-56f27b7e-ab3f-4c3e-b010-e179933551d3.png)

**Comment by tgorm1965** [comment]
I'm seeing it but the cseg is white for me. Do I have to assign the vertices to the vertex colour I have defined ?

**Comment by HugoCMU** [comment]
If you manually painted the object you shouldn't need to assign the vertex color properties in the code. Do you get a white segmentation image when you click the `Render` button in the zpy panel?
![image](https://user-images.githubusercontent.com/8493427/126071985-10bca770-91c8-4531-94f3-3e5d4ef8ee3d.png)
