### ISSUE TITLE
Allow Custom scaling for HDRI Background

### ISSUE THREAD

**Issue by Resh-97** [ZumoLabs/zpy#132]
Hi,
This is a small feature I'd like to be added to "**zpy.hdris.random_hdri()**" function.
Currently, the function doesn't accept a custom scale from user and renders the HDRI background in the default scale w.r.t the 3D object. 

It would helpful if a parameter can be added to **random_hdri()** so that it can be passed to **load_hdri()**. This would allow us to play with the HDRI background scaling.

<img width="503" alt="hdri" src="https://user-images.githubusercontent.com/66821775/123507168-9bee1d00-d685-11eb-8589-5307c27e153f.png">

**Comment by HugoCMU** [comment]
Added scale as a kwarg to the `random_hdri` function: https://github.com/ZumoLabs/zpy/commit/c16f9884d5477ccdf1986af2c3403d5c28d2e7e5

**Comment by HugoCMU** [comment]
@Resh-97 Just a heads up it seems like the best way to change the perceived HDRI scale is to change the FOV [(screenshot link)](https://www.aifosdesign.se/tutorial-how-to-use-an-hdri-environment-texture-in-blender/)
![image](https://user-images.githubusercontent.com/8493427/123577255-549c8500-d788-11eb-9b70-f368d727d9d4.png)

**Comment by Resh-97** [comment]
"Perceived HDRI scale"- Thats right, I was searching for the right term @HugoCMU. 

 Thanks, so I guess it boils down to tweaking the focal length. 
 I'll see how it can be done from the script.

**Comment by HugoCMU** [comment]
[This is the property for FOV](https://docs.blender.org/api/current/bpy.types.Camera.html#bpy.types.Camera.lens), though I think it will probably be easier to tune within the Blender GUI first.
