### ISSUE TITLE
Improving Rendering & Processing Speed with AWS

### ISSUE THREAD

**Issue by tgorm1965** [ZumoLabs/zpy#135]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by the time it is taking to process images on my local device (the rendering isn't the worst but the annotations are taking a long time at the end). I would like to use AWS EC2 instances to reduce the time required to create images and annotations (especially the category segmentation which seems to take a long time to encode into the annotation). 

Do you have any suggestions as to the kinds of instances or methods on AWS can be used to reduce rendering and processing time? That would be immensely helpful. Thank you.

**Comment by HugoCMU** [comment]
We have a CLI that allows you to upload a local blender simulation and generate images in the cloud. More info on the CLI in our [docs](https://zumolabs.github.io/zpy/cli/about/). You can also view and download these datasets on our [webapp](https://app.zumolabs.ai/). A quick caveat though: we just pushed a bunch of changes to the CLI & WebApp today, so it might be buggy (we love feedback).

**Comment by nponte-zumo** [comment]
The way we see it the local device is just intended to be used for debugging. We provide the setup to generate images from a sim using our configured backend using our WebApp (https://app.zumolabs.ai) and cli (https://zumolabs.github.io/zpy/cli/about/). 

Through the addon you should be able to export the sim and then using the cli you should be able to upload the sim and generate datasets from the sim.

```
zpy sim upload <sim_name> path/to/exported/sim.zip
zpy dataset generate <dataset_name> <sim_name> <num_frames>
```

then you should be able to view the dataset on
https://app.zumolabs.ai/datasets

Let me know when you create an account and we can enable 5k in free generation credits for you.

**Comment by HugoCMU** [comment]
You can export a local simulation by hitting the `Export Sim` button on the zpy addon panel:
![image](https://user-images.githubusercontent.com/8493427/125023052-e9c63600-e032-11eb-8616-937c3b5f9b1e.png)

**Comment by tgorm1965** [comment]
Ok my username is tgorm and I've tried uploading using zpy upload sim but i get the following error: No such command 'sim'.. Any fix for this?

**Comment by nponte-zumo** [comment]
This new cli format went live earlier today. I would make sure your `zpy-zumo` python package is at version `1.3.0`

**Comment by tgorm1965** [comment]
Yep, I just did a new pip install of zpy-zumo, so I'm unsure if that is the issue. Is this what you mean or do you mean the package in. Blender?

**Comment by nponte-zumo** [comment]
Yes you will also need to update the `zpy-zumo` the addon is using as we export more information from scenes from before.

The error on the command ```zpy sim upload``` no such command sim is usually due to our new CLI swapping from ```zpy upload sim``` to ```zpy sim upload```

**Comment by tgorm1965** [comment]
Ok I will do that. Also another question regarding your generation times. If I want a full HD 1080p image and roughly 75% of the image needs to be segmented into categories, how long would something like that take per sim step in your experience?

**Comment by nponte-zumo** [comment]
After uploading the sim you can see the amount of time in seconds it will take to generate one step. Hard to tell without running it and seeing how the objects are loading and such.

https://app.zumolabs.ai/sims/fb6d9af9-3b17-4c9c-b9bd-784f08ccd24c/metadata

**Comment by tgorm1965** [comment]
Ok sounds good. And if I run out of generation credits how much do they cost moving forward?

**Comment by nponte-zumo** [comment]
Still something we are figuring out ourselves. Would love feedback to what would feel good from a user perspective. 

Our current implementation is some cost per time spent running on the machines which is correlated to our own spending costs.

**Comment by tgorm1965** [comment]
Hey, I'll need to try itout before giving feedback I think. 

Im currently getting this error when trying to run the sim: raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0). Could you help me resolve this please

**Comment by nponte-zumo** [comment]
![Screen Shot 2021-07-09 at 9 01 39 AM](https://user-images.githubusercontent.com/58713354/125106270-4f96da00-e094-11eb-8ea7-3c2e77750bd0.png)

The sim failed to ingress so you will be unable to generate images from it until the sim ingress is successful. I believe this error is related to the sim being exported with the old version of the client `1.2.3` as you can see above.

**Comment by nponte-zumo** [comment]
@tgorm1965 

Just added backwards compatibility for old scenes so you should be able to upload the current sim you have and have it ingress successfully if you want to give it another shot.
