### ISSUE TITLE
Cannot create COCO annotations when RGB and Segmentation images are in Separate folder

### ISSUE THREAD

**Issue by aadi-mishra** [ZumoLabs/zpy#145]
Hi ,
I am trying to generate data with annotations, where my `output_dir` is the parent folder and I save my RGB and ISEG images in the children folders for example `data/rgb_images` and `data/iseg_images`. I also have another folder for annotations as `data/coco_annotations`. I am successfully able to render images however, I cannot generate COCO annotations. As far as I understand from the source code, it parses image path w.r.t. the `saver.output_dir + filename` instead of the directories where images are actually stored. 

Thanks!!!

**Comment by HugoCMU** [comment]
Images are [stored in a dictionary](https://github.com/ZumoLabs/zpy/blob/bc799765115259d90fa84739e0cca2b3ca435cb7/zpy/saver_image.py#L22) inside the saver object. When you add an image to the saver, you provide the [name](https://github.com/ZumoLabs/zpy/blob/bc799765115259d90fa84739e0cca2b3ca435cb7/examples/package/run.py#L174) which will be used as the key. You should use this same image name when [adding an annotation](https://github.com/ZumoLabs/zpy/blob/bc799765115259d90fa84739e0cca2b3ca435cb7/examples/package/run.py#L195) to the saver object. To output COCO annotations you must write out the saver object at the end of the run script, [as in this example](https://github.com/ZumoLabs/zpy/blob/bc799765115259d90fa84739e0cca2b3ca435cb7/examples/package/run.py#L212).

**Comment by aadi-mishra** [comment]
Hi Hugo, 
Thanks for the prompt response! 
I understood what you meant and I believe I am doing the same as you suggested. 

Here's what I have done. As you can see, instead of having common directory I have separated RGB and ISEG images. 

       zpy.render.render_aov(
            rgb_path = saver.output_dir / "rgb_images" / rgb_image_name,
            iseg_path = saver.output_dir / "iseg_images" / iseg_image_name,
            width = 640,
            height=480,
        )
        
        saver.add_image(
            name=rgb_image_name,
            style='default',
            output_path=saver.output_dir / "rgb_images" / rgb_image_name,
            frame=image_id,
            width=640,
            height=480,
        )
    
        saver.add_image(
            name=iseg_image_name,
            style='default',
            output_path=saver.output_dir / "iseg_images" / iseg_image_name,
            frame=image_id,
            width=640,
            height=480,
        )
        
        saver.add_annotation(
            image=rgb_image_name,
            seg_image=iseg_image_name,
            seg_color=profile_seg_color,
            category='profile',
        )
    
    saver.output_annotated_images()
    saver.output_meta_analysis()
    zpy.output_coco.OutputCOCO(saver).output_annotations()


I am getting following error 
`zpy.output_coco.COCOParseError: image path /home/aadi/Documents/ProjectArbeit2021/StA_Mishra/09_Rendered_Images/image_000000_rgb.png does not exist
  In call to configurable 'parse_coco_annotations' (<function parse_coco_annotations at 0x7fcfcf557790>)
  In call to configurable 'output_annotations' (<function OutputCOCO.output_annotations at 0x7fcfcf557820>)`

**Comment by HugoCMU** [comment]
One quick thing I noticed, the instance segmentation image should be of style `segmentation`, like this:
```
saver.add_image(
    name=iseg_image_name,
    style='segmentation',
    ...
```
Apart from that I think your diagnosis is correct: the saver assumes the image is stored in `saver.output_dir / image_name`, so having those intermediate folders is going to result in this FileNotFound bug. The easy fix would be to get rid of the intermediate folders, as such:
```
   zpy.render.render_aov(
        rgb_path = saver.output_dir / rgb_image_name,
        iseg_path = saver.output_dir / iseg_image_name,
     ...
```
Admittedly that might require some changes downstream (whatever dataloader / training code you have that is using this COCO dataset).

**Comment by aadi-mishra** [comment]
Thanks! 
I'll do that. 
For now I think writing another script to separate the data should work.
Nevertheless it would be great to have this feature in the future release.
