### ISSUE TITLE
Can't get denoised render from zpy generated dataset

### ISSUE THREAD

**Issue by RamiroVolt** [ZumoLabs/zpy#151]
First I tried to set denoise on the run.py exemple like this:

![image](https://user-images.githubusercontent.com/33462966/142673564-48e138e0-15cf-4618-88c1-8f693e43f18d.png)

With no success I went to the 'Blender 2.93\2.93\python\lib\site-packages\zpy\render.py' file and change some lines there too. 

![image](https://user-images.githubusercontent.com/33462966/142673696-2efcf556-a5f6-4584-bd2e-112a800e69f9.png)

Still the images are being generated with a high level of noise, like this one.

![image](https://user-images.githubusercontent.com/33462966/142673762-913bd596-337c-479d-ab1b-f3f189803863.png)

What should I do to get a denoiser like 'OPTIX' to work on my synthetic dataset?

**Comment by HugoCMU** [comment]
Based on [Blender's API](https://docs.blender.org/api/current/bpy.types.Scene.html?highlight=cyclesrendersettings#bpy.types.Scene.cycles) lookup it seems like the `scene.cycles.______` properties are read-only. If you want to add denoising you can try adding a [Denoiser node](https://docs.blender.org/api/current/bpy.types.CompositorNodeDenoise.html?highlight=denoise#bpy.types.CompositorNodeDenoise) in the compositor node graph.

**Comment by RamiroVolt** [comment]
Thanks @HugoCMU , It worked!
