### ISSUE TITLE
Attributerror: "rendersettings" object has no attribute "tile_x" (blender 3.0)

### ISSUE THREAD

**Issue by lorepieri8** [ZumoLabs/zpy#152]
**Describe the bug**
Attributerror: "rendersettings" object has no attribute "tile_x" when pressing the render button in the add-on.

 - Blender 3.0
 - Mac OS

**Additional context**
No problems in Blender 2.93.

**Comment by HugoCMU** [comment]
A quick fix for this would be to [comment out these lines](https://github.com/ZumoLabs/zpy/blob/be4eaf77cab9241038d7d7afe2cb1c7694b41b80/zpy/render.py#L310) in the zpy source code.
