### ISSUE TITLE
Single bounding box for multiple instances

### ISSUE THREAD

**Issue by lorepieri8** [ZumoLabs/zpy#153]
**Describe the bug**
A Single bounding box for multiple instances, instead of 1 bounding box for each instance.

https://imgur.com/a/FhnDvNs
(two cans detected in a  single bbox)

**To Reproduce**
Import two objects in the scene and associate them to the same category. Perform the segmentation, e.g. following the suzanne tutorial.

**Additional context**
Segmentation correctly shows two separate objects, but the bounding box is common to both the objects, as if the two objects were a single entity.

**Comment by HugoCMU** [comment]
Looks like both cans are segmented with the same color. There are two different types of segmentation: category and instance. Instance (`iseg`) is always unique, but category (`cseg`) is used for groups of like objects. Are you using the same category color for both objects when creating the segmentation image?

**Comment by lorepieri8** [comment]
Yes, I was segmenting the instances with the same color assigned to the category. By segmenting with individual colours and saving the annotations with those colours I managed to get individual bboxes.

Thanks for the quick reply and good job with the project.
