### ISSUE TITLE
Headless Execution Instructions

### ISSUE THREAD

**Issue by vicentelobo** [ZumoLabs/zpy#157]
Hello!

I want to execute ZPY using a server, so I'm looking for headless execution. Do you have any documentation on how to use it?

I tried using directly the run.py file: `blender -b file.blend -P path/to/run.py` and using a script that simulates the run button in the addon: `blender -b file.blend -P path/to/execute_zpy.py`.

execute_zpy.py:
```python
import bpy
import gin
import zpy

zpy.blender.load_text_from_file(
    "/absolute/path/to/config.gin",
    text_name="config",
)
zpy.blender.load_text_from_file(
    "/absolute/path/to/run.py",
    text_name="run",
)

zpy.logging.set_log_levels("debug")
run_text = bpy.data.texts.get("run", None)
if run_text is None:
    raise ValueError(
        'Running a sim requires a run text, could not find in text with name "run".'
    )
gin.enter_interactive_mode()
with gin.unlock_config():
    run_text_as_module = run_text.as_module()
zpy.blender.parse_config("config")
run_text_as_module.run()
```
In both situations, I can start the script and ZPY starts running, but it raises an Exception when I try to use `zpy.objects.jitter` inside my `run.py`. Exception traceback: 
```
  File "blender-2.93.8-linux-x64/2.93/python/lib/python3.9/site-packages/zpy/objects.py", line 549, in jitter
    rotate(
  File "blender-2.93.8-linux-x64/2.93/python/lib/python3.9/site-packages/zpy/objects.py", line 455, in rotate
    select(obj)
  File "blender-2.93.8-linux-x64/2.93/python/lib/python3.9/site-packages/zpy/objects.py", line 87, in select
    bpy.ops.object.select_all(action="DESELECT")
  File "blender-2.93.8-linux-x64/2.93/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.select_all.poll() failed, context is incorrect
```

Since this error doesn't happen when I run it through the addon, I imagine it's something I'm doing wrong in headless execution and that's why I came here looking for instructions for this.

Thanks in advance!

Blender version: 2.93.8
ZPY version: 1.4.1rc9

**Comment by hu-po** [comment]
Thanks for taking the time to write this well asked question. Running Blender headless requires building it from source with some special flags. Your solution `execute_zpy.py` seems close, but debugging it is going to be quite difficult. Behind the scenes we had a fairly complicated flow to execute sims on various forms of compute.

This repo isn't actively maintained anymore (I am just here doing graveyard shifts). I would recommend using something like [Kubric](https://github.com/google-research/kubric). Its basically the same thing as zpy, but it is being actively developed and maintained.

**Comment by vicentelobo** [comment]
Hi Hugo. Thanks for your reply and sorry for my delay.

Got your point.
It wouldn't be a problem for me to build Blender from the source, but I understand that given that the repository is no longer being maintained, it doesn't make sense to add this information now. I will solve my problem using the default zpy workflow and close the issue.

It's sad that you guys aren't maintaining this library anymore, as I think it's pretty good, and looking at it quickly, Kubric didn't seem to solve my problem.

Anyway, thank you so much for the reply and for all the work you all put in to making this project!
