### ISSUE TITLE
Bump map jittering

### ISSUE THREAD

**Issue by HugoCMU** [ZumoLabs/zpy#16]
Add jittering of bump map to material jittering options.

**Comment by kursad-zumolabs** [comment]
One way we can frame this is with perturbing the incoming normals and jittering UV coordinates, however this can be a bit complicated if there exists a prior bump map setup with multiple nodes.


https://user-images.githubusercontent.com/67970138/110831913-58031380-8260-11eb-918a-fa498232127b.mp4
