### ISSUE TITLE
AOV Pass Error

### ISSUE THREAD

**Issue by yashdutt20** [ZumoLabs/zpy#39]
**Describe the bug**
A key error is occurring in zpy. Can you help me figure out how to fix this?

**To Reproduce**
I have followed the Suzanne script from the first video of the youtube channel.

**Expected behavior**
To save and render the images.

**Screenshots**
  File "/Applications/Blender.app/Contents/Resources/2.91/python/lib/python3.7/site-packages/zpy/render.py", line 42, in make_aov_pass
    view_layer['aovs'][-1]['name'] = style
KeyError: 'bpy_struct[key]: key "aovs" not found'
  In call to configurable 'make_aov_pass' (<function make_aov_pass at 0x1576194d0>)
  In call to configurable 'make_aov_file_output_node' (<function make_aov_file_output_node at 0x15761db00>)
  In call to configurable 'render_aov' (<function render_aov at 0x157623560>)
Error: Python script failed, check the message in the system console
Executing script failed with exception Error: Python script failed, check the message in the system console

 
**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.5
 - latest zpy

**Comment by yashdutt20** [comment]
I seemed to have moved pass this issue after reinstalling zpy 0.9.13 but now this error is occuring: 
  File "/Applications/Blender.app/Contents/Resources/2.91/python/lib/python3.7/site-packages/zpy/render.py", line 36, in make_aov_pass
    for aov in view_layer.aovs.values():
AttributeError: 'ViewLayer' object has no attribute 'aovs'
  In call to configurable 'make_aov_pass' (<function make_aov_pass at 0x177b6e320>)
  In call to configurable 'make_aov_file_output_node' (<function make_aov_file_output_node at 0x177b6ec20>)
  In call to configurable 'render_aov' (<function render_aov at 0x177b63e60>)

I am kind of lost now so any help is much appreciated!

**Comment by kursad-zumolabs** [comment]
Hi

Please try it with Blender 2.92 release.

**Comment by yashdutt20** [comment]
Yeah I just tried it with 2.92 and it works fine now
