### ISSUE TITLE
Better Run button

### ISSUE THREAD

**Issue by HugoCMU** [ZumoLabs/zpy#65]
To properly run the "run" script, a zpy user has to click the "Run" button under the ZPY panel. If they click the "Run" button in the Blender script panel, it will not save and reset the scene, resulting in simulation drift. We should provide a warning, or simply make the "run" button in the blender script also a valid option.

**Comment by HugoCMU** [comment]
> clicking the Run button in the Execute Panel is causing Blender to fudge the context in some way? I've tried smaller versions of the scripts and run them from the text editor's run button and they work fine, it's when you use the zpy Run function that things go wrong

**Comment by HugoCMU** [comment]
Object selection does not change `bpy.context.active_object`
![image](https://user-images.githubusercontent.com/8493427/116431310-8632b780-a7fc-11eb-9b77-e6b5ee90cc9a.png)

**Comment by HugoCMU** [comment]
![image](https://user-images.githubusercontent.com/8493427/116434770-8ed8bd00-a7ff-11eb-9ace-957e01198233.png)

**Comment by sammiezumo** [comment]
![image](https://user-images.githubusercontent.com/79859060/116447192-f3524700-a814-11eb-857a-590b2b158142.png)

**Comment by sammiezumo** [comment]
selection != active object is what I've found so far. This snippet clears both selection and active object, then sets again. Works to select the object but doesn't seem to fix the problem with the make objects real operator.

**Comment by HugoCMU** [comment]
Might have found a clue here. There seems to be a difference between "active" and "selected"
![image](https://user-images.githubusercontent.com/8493427/116454574-fc431880-a814-11eb-9388-785a4e0f6bfb.png)

**Comment by HugoCMU** [comment]
Also hitting Play button on the script does not cause this:
![image](https://user-images.githubusercontent.com/8493427/116455669-34972680-a816-11eb-9857-6f9522ee71e2.png)
