### ISSUE TITLE
Nice Docs

### ISSUE THREAD

**Issue by HugoCMU** [ZumoLabs/zpy#66]
Refactor README to show upcoming public simulations `shelf` and `package`.

**Comment by HugoCMU** [comment]
github.io

**Comment by HugoCMU** [comment]
react query doc markups: https://github.com/tannerlinsley/react-query/tree/master/docs/src/pages/reference
react query doc website: https://react-query.tanstack.com/overview

**Comment by nponte-zumo** [comment]
https://zumolabs.github.io/zpy
