### ISSUE TITLE
Fix Dataset Inheritance

### ISSUE THREAD

**Issue by HugoCMU** [ZumoLabs/zpy#68]
Seeing some issues around not having explicit links between Jobs and the generic DataSets which make up the input_data_sets and output_data_sets. Keeping track of the things I wanted to do in the UI but couldn't:

1) Link directly from a Job and show a view for the specific kind of DataSet (Generated/Uploaded/Job).

The list of input_data_sets on a Job can be one of 3 types, but given an instance of DataSet we can't convert to an instance of one of the 3 types
Current workaround: only showing id, name, and images for any input_data_sets in the UI
Fix: not really sure, some ideas:
-- Add just a type field on the base DataSet and then add rigging into the base DataSetViewSet and DataSetSerialzier that will delegate to the appropriate DataSetViewSet or DataSetSerializer.
-- Add a type field to the base DataSet model, move all "custom" fields from the child type DataSets into the base DataSet model and make them blank-able or maybe nullable, hook validation into the model/serializers to make sure correct fields are being used with each type, and remove the child models entirely and only work with DataSets again
-- In both cases, we'd only be using a /api/v1/data-sets end point
2) Get a paginated response for the input_data_sets on a Job

I can't do something of this nature
jobs_router = router.register(r'jobs', JobViewset, basename='job')
jobs_router.register(r'input-data-sets', DataSetViewset, basename='job-inputdataset', parents_query_lookups=['job'])
because there is no link between a generic DataSet and a Job (I think)

Current workaround: returning ALL input_data_sets in a Job detail request.
Fix: not really sure, but I don't think this is possible with the first thought to fix the first issue above, might need to do the 2nd option so that we can filter on fields that don't necessarily belong to a certain type

**Comment by nponte-zumo** [comment]
https://github.com/ZumoLabs/alfred/issues/439 no more dataset types.
