### ISSUE TITLE
CLI Doc Gifs

### ISSUE THREAD

**Issue by HugoCMU** [ZumoLabs/zpy#89]
Some of the gifs in the CLI docs are really large/long. 

![image.png](https://images.zenhubusercontent.com/5e94c8121e62773ba211ac82/ad5e6210-e98f-46f5-93bd-320a66300623)

**Comment by nponte-zumo** [comment]
https://github.com/ZumoLabs/zpy/issues/66. Wont be relevant here

**Comment by HugoCMU** [comment]
Still happening on docs website.
